# Generated by Django 3.1.7 on 2021-04-01 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transactions_num', models.IntegerField(verbose_name='No of Transactions')),
                ('max_price', models.IntegerField(verbose_name='Max Price')),
                ('min_price', models.IntegerField(verbose_name='Min Price')),
                ('close_price', models.IntegerField(verbose_name='Close Price')),
                ('traded_shares', models.IntegerField(verbose_name='Traded Shares')),
                ('total_amt', models.IntegerField(verbose_name='Total Amount')),
                ('prev_close', models.IntegerField(verbose_name='Previous Close Price')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('records', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='scrape.stockrecord')),
            ],
        ),
    ]
