# Generated by Django 3.1.7 on 2021-04-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='records',
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='scrape.stock'),
            preserve_default=False,
        ),
    ]
