# Generated by Django 3.1.7 on 2021-04-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_auto_20210401_0445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='close_price',
            field=models.FloatField(verbose_name='Close Price'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='max_price',
            field=models.FloatField(verbose_name='Max Price'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='min_price',
            field=models.FloatField(verbose_name='Min Price'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='prev_close',
            field=models.FloatField(verbose_name='Previous Close Price'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='traded_shares',
            field=models.FloatField(verbose_name='Traded Shares'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='transactions_num',
            field=models.FloatField(verbose_name='No of Transactions'),
        ),
    ]
