# Generated by Django 3.1.7 on 2021-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_auto_20210401_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='total_amt',
            field=models.FloatField(verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='traded_shares',
            field=models.IntegerField(verbose_name='Traded Shares'),
        ),
    ]
