# Generated by Django 3.1.7 on 2021-04-04 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_auto_20210401_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
