# Generated by Django 3.1.7 on 2021-04-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_auto_20210404_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='state',
            field=models.CharField(choices=[('fetch', 'fetch'), ('ready', 'ready'), ('error', 'error')], default='fetch', max_length=10),
        ),
    ]
